/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.cpp                                           :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: hchaguer <hchaguer@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2024/01/21 22:05:34 by hchaguer          #+#    #+#             */
/*   Updated: 2024/01/23 11:35:39 by hchaguer         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "Base.hpp"
#include <unistd.h>

int main()
{
    Base* b = Base::generate();    /* It randomly create an instance A, B or C */
    // Base::identify(b);          /* it print the actual type of object generated by generate() function */
    // Base::identify(*b);        /* it print the actual type of object generated by generate() function */
    delete b;
    
    // sleep(1);
    // std::cout << "-------------------------------" << std::endl;
    // Base *b1 = Base::generate();
    // Base::identify(b1);
    // Base::identify(*b1);
    
    // delete b1;
    return 0;
}